global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'servicea'
    static_configs:
      - targets: ['host.docker.internal:5001']
  - job_name: 'serviceb'
    static_configs:
      - targets: ['host.docker.internal:5002'] 